const KEY="faeza_store_erp_v2";const demo={products:[
{id:1,barcode:"8991001",name:"Indomie Goreng",cat:"Sembako",buy:2500,sell:3500,stock:24,min:8},
{id:2,barcode:"8991002",name:"Gula Pasir 1 Kg",cat:"Sembako",buy:15000,sell:17500,stock:6,min:8},
{id:3,barcode:"8991003",name:"Minyak Goreng 1 L",cat:"Sembako",buy:16000,sell:19000,stock:14,min:5},
{id:4,barcode:"8991004",name:"Teh Celup",cat:"Minuman",buy:7000,sell:9500,stock:18,min:5},
{id:5,barcode:"8991005",name:"Air Mineral 600ml",cat:"Minuman",buy:2000,sell:3000,stock:30,min:10}],sales:[],suppliers:[],debts:[],expenses:[]};
let db=JSON.parse(localStorage.getItem(KEY)||"null")||demo,cart=[];const rp=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n),save=()=>localStorage.setItem(KEY,JSON.stringify(db));
document.getElementById("menu").onclick=()=>document.getElementById("nav").classList.toggle("open");document.querySelectorAll("#nav button").forEach(b=>b.onclick=()=>go(b.dataset.page));
function go(id){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));document.getElementById(id).classList.add("active");document.getElementById("nav").classList.remove("open");render()}
function render(){dash();renderPOS();products();stocks();suppliers();debts();report()}
function dash(){let d=new Date().toISOString().slice(0,10),s=db.sales.filter(x=>x.date.slice(0,10)==d),om=s.reduce((a,x)=>a+x.total,0),lb=s.reduce((a,x)=>a+x.profit,0),low=db.products.filter(x=>x.stock<=x.min);document.getElementById("omzet").textContent=rp(om);document.getElementById("trx").textContent=s.length;document.getElementById("laba").textContent=rp(lb);document.getElementById("menipis").textContent=low.length;document.getElementById("dashStock").innerHTML=low.map(p=>`<div class="row"><span>${p.name}</span><b class="danger">${p.stock}</b></div>`).join("")||"Semua stok aman.";document.getElementById("dashSales").innerHTML=db.sales.slice(-5).reverse().map(x=>`<div class="row"><span>${x.invoice}</span><span>${rp(x.total)}</span></div>`).join("")||"Belum ada transaksi."}
function renderPOS(){let q=(document.getElementById("search")?.value||"").toLowerCase();document.getElementById("posProducts").innerHTML=db.products.filter(p=>(p.name+" "+p.barcode).toLowerCase().includes(q)).map(p=>`<div class="product"><small>${p.barcode}</small><b>${p.name}</b><span>${rp(p.sell)} • stok ${p.stock}</span><br><br><button onclick="addCart(${p.id})">Tambah</button></div>`).join("");document.getElementById("cart").innerHTML=cart.map(c=>{let p=db.products.find(x=>x.id==c.id);return `<div class="row"><span>${p.name}</span><span>${c.qty}x</span><span>${rp(p.sell*c.qty)}</span><button onclick="qty(${p.id},-1)">−</button></div>`}).join("")||"Keranjang kosong";let t=cart.reduce((a,c)=>a+db.products.find(p=>p.id==c.id).sell*c.qty,0);document.getElementById("total").textContent=rp(t)}
function addCart(id){let p=db.products.find(x=>x.id==id);if(!p||p.stock<1)return;let c=cart.find(x=>x.id==id);if(c){if(c.qty<p.stock)c.qty++}else cart.push({id,qty:1});renderPOS()}function qty(id,d){let c=cart.find(x=>x.id==id);if(!c)return;c.qty+=d;if(c.qty<=0)cart=cart.filter(x=>x.id!=id);renderPOS()}function clearCart(){cart=[];renderPOS()}
function pay(){if(!cart.length)return alert("Keranjang kosong.");let total=cart.reduce((a,c)=>a+db.products.find(p=>p.id==c.id).sell*c.qty,0),paid=+document.getElementById("paid").value;if(paid<total)return alert("Pembayaran kurang.");let profit=0;cart.forEach(c=>{let p=db.products.find(x=>x.id==c.id);p.stock-=c.qty;profit+=(p.sell-p.buy)*c.qty});db.sales.push({invoice:"INV-"+Date.now().toString().slice(-8),date:new Date().toISOString(),total,profit,items:cart});save();alert("Berhasil. Kembalian "+rp(paid-total));cart=[];document.getElementById("paid").value="";render()}
function products(){document.getElementById("productsTable").innerHTML='<div class="row"><b>Produk</b><b>Jual</b><b>Stok</b><b>Aksi</b></div>'+db.products.map(p=>`<div class="row"><span>${p.name}<small> • ${p.cat}</small></span><span>${rp(p.sell)}</span><span class="${p.stock<=p.min?'danger':''}">${p.stock}</span><button onclick="delProduct(${p.id})">Hapus</button></div>`).join("")}
function stocks(){document.getElementById("stockTable").innerHTML='<div class="row"><b>Produk</b><b>Stok</b><b>Min</b><b>Status</b></div>'+db.products.map(p=>`<div class="row"><span>${p.name}</span><span>${p.stock}</span><span>${p.min}</span><span class="${p.stock<=p.min?'danger':''}">${p.stock<=p.min?"MENIPIS":"AMAN"}</span></div>`).join("")}
function suppliers(){document.getElementById("supplierTable").innerHTML=db.suppliers.map(s=>`<div class="row"><span>${s.name}</span><span>${s.phone||"-"}</span><button onclick="delSupplier(${s.id})">Hapus</button></div>`).join("")||"Belum ada supplier."}
function debts(){let h=db.debts.filter(x=>x.type=="hutang").reduce((a,x)=>a+x.amount-x.paid,0),p=db.debts.filter(x=>x.type=="piutang").reduce((a,x)=>a+x.amount-x.paid,0);document.getElementById("hutangTotal").textContent=rp(h);document.getElementById("piutangTotal").textContent=rp(p);document.getElementById("debtTable").innerHTML=db.debts.map(x=>`<div class="row"><span>${x.name}</span><span>${x.type}</span><span>${rp(x.amount-x.paid)}</span><button onclick="payDebt(${x.id})">Bayar</button></div>`).join("")||"Belum ada catatan."}
function report(){let om=db.sales.reduce((a,x)=>a+x.total,0),lb=db.sales.reduce((a,x)=>a+x.profit,0),h=db.debts.filter(x=>x.type=="hutang").reduce((a,x)=>a+x.amount-x.paid,0),p=db.debts.filter(x=>x.type=="piutang").reduce((a,x)=>a+x.amount-x.paid,0);document.getElementById("report").innerHTML=`<div class="row"><span>Total omzet</span><b>${rp(om)}</b></div><div class="row"><span>Laba kotor</span><b>${rp(lb)}</b></div><div class="row"><span>Hutang berjalan</span><b>${rp(h)}</b></div><div class="row"><span>Piutang berjalan</span><b>${rp(p)}</b></div><div class="row"><span>Total produk</span><b>${db.products.length}</b></div>`}
function modal(body){document.getElementById("modal").innerHTML=`<div class="box">${body}</div>`;document.getElementById("modal").className="modal show"}function close(){document.getElementById("modal").className="modal"}
function addProduct(){modal(`<h3>Tambah Produk</h3><input id="n" placeholder="Nama"><br><br><input id="b" placeholder="Barcode"><br><br><input id="buy" type="number" placeholder="Harga beli"><br><br><input id="sell" type="number" placeholder="Harga jual"><br><br><input id="st" type="number" placeholder="Stok"><br><br><button class="gold" onclick="saveProduct()">Simpan</button> <button onclick="close()">Batal</button>`)}
function saveProduct(){let n=document.getElementById("n").value.trim();if(!n)return alert("Nama wajib.");db.products.push({id:Date.now(),barcode:document.getElementById("b").value||Date.now(),name:n,cat:"Umum",buy:+document.getElementById("buy").value||0,sell:+document.getElementById("sell").value||0,stock:+document.getElementById("st").value||0,min:5});save();close();render()}function delProduct(id){if(confirm("Hapus produk?")){db.products=db.products.filter(x=>x.id!=id);save();render()}}
function stockIn(){let o=db.products.map(p=>`<option value="${p.id}">${p.name}</option>`).join("");modal(`<h3>Stok Masuk</h3><select id="sp">${o}</select><br><br><input id="sq" type="number" placeholder="Jumlah"><br><br><button class="gold" onclick="saveStock()">Simpan</button> <button onclick="close()">Batal</button>`)}
function saveStock(){let p=db.products.find(x=>x.id==document.getElementById("sp").value),q=+document.getElementById("sq").value;if(!p||q<1)return alert("Jumlah tidak valid.");p.stock+=q;save();close();render()}
function addSupplier(){modal(`<h3>Tambah Supplier</h3><input id="sn" placeholder="Nama supplier"><br><br><input id="ph" placeholder="No. WhatsApp"><br><br><button class="gold" onclick="saveSupplier()">Simpan</button> <button onclick="close()">Batal</button>`)}function saveSupplier(){let n=document.getElementById("sn").value.trim();if(!n)return;db.suppliers.push({id:Date.now(),name:n,phone:document.getElementById("ph").value});save();close();render()}function delSupplier(id){db.suppliers=db.suppliers.filter(x=>x.id!=id);save();render()}
function addDebt(){modal(`<h3>Catat Hutang/Piutang</h3><select id="dt"><option value="hutang">Hutang</option><option value="piutang">Piutang</option></select><br><br><input id="dn" placeholder="Nama"><br><br><input id="da" type="number" placeholder="Nominal"><br><br><button class="gold" onclick="saveDebt()">Simpan</button> <button onclick="close()">Batal</button>`)}function saveDebt(){db.debts.push({id:Date.now(),type:document.getElementById("dt").value,name:document.getElementById("dn").value,amount:+document.getElementById("da").value,paid:0});save();close();render()}function payDebt(id){let d=db.debts.find(x=>x.id==id);let q=+prompt("Nominal pembayaran",d.amount-d.paid)||0;d.paid=Math.min(d.amount,d.paid+q);save();render()}
function backup(){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:"application/json"}));a.download="faeza-store-backup.json";a.click()}function restore(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{db=JSON.parse(r.result);save();render();alert("Backup berhasil dipulihkan.")}catch{alert("File backup tidak valid.")}};r.readAsText(f)}function resetData(){if(confirm("Hapus semua data dan kembali ke data demo?")){localStorage.removeItem(KEY);location.reload()}}
if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js").catch(()=>{});render();